import { MigrationInterface, QueryRunner } from "typeorm";

export class auto1695637704607 implements MigrationInterface {
    name = 'auto1695637704607'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "component" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "price" integer NOT NULL DEFAULT '1', "unit" character varying NOT NULL DEFAULT 'Pieces', "balance" integer NOT NULL DEFAULT '0', "archived" boolean NOT NULL DEFAULT false, "pointId" uuid, CONSTRAINT "PK_c084eba2d3b157314de79135f09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "component_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "pointId" uuid, CONSTRAINT "PK_ed1d2b14c143b2cba50df16ca4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consumption_component" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "amount" integer NOT NULL DEFAULT '1', "componentId" uuid, "for_product" uuid, CONSTRAINT "PK_6b5a45affba5cf34af007dc4652" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "price" integer NOT NULL DEFAULT '1', "unit" character varying NOT NULL DEFAULT 'Pieces', "sales_unit" integer NOT NULL DEFAULT '1', "archived" boolean NOT NULL DEFAULT false, "pointId" uuid, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "pointId" uuid, CONSTRAINT "PK_0dce9bc93c2d2c399982d04bef1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "tenantId" uuid, CONSTRAINT "PK_8ea75b2a26f83f3bc98b9c6aaf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "priority" integer NOT NULL, "orderTypeId" uuid, "statusId" uuid, CONSTRAINT "PK_4d6cfcfcf4325a751f799cd0535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "archived" boolean NOT NULL DEFAULT false, "pointId" uuid, CONSTRAINT "PK_0ff5747bd2cb60f2465351121f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "balance" integer NOT NULL DEFAULT '0', "pointId" uuid, CONSTRAINT "PK_f3246deb6b79123482c6adb9745" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "system" boolean NOT NULL, "archived" boolean NOT NULL DEFAULT false, "pointTenantid" uuid, "pointId" uuid NOT NULL DEFAULT uuid_generate_v4(), "pointCreated_at" TIMESTAMP NOT NULL DEFAULT now(), "pointUpdated_at" TIMESTAMP NOT NULL DEFAULT now(), "pointName" character varying NOT NULL, "pointAddress" character varying NOT NULL, CONSTRAINT "PK_2dc4a0d7e57c02e67b63fd2e92b" PRIMARY KEY ("id", "pointId"))`);
        await queryRunner.query(`CREATE TABLE "payment_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "payment_method" uuid, "sale_point" uuid, "bank_account" uuid, CONSTRAINT "PK_0f9650efa36bead30593038140c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_point" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "display" boolean NOT NULL, "archived" boolean NOT NULL DEFAULT false, "pointId" uuid, CONSTRAINT "PK_2d14d5cd80162ab549de1ee05ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "phone" character varying NOT NULL, "balance" integer NOT NULL DEFAULT '0', "tenantId" uuid, CONSTRAINT "PK_96da49381769303a6515a8785c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "statusId" uuid, "orderId" uuid, "userId" uuid, CONSTRAINT "PK_efde6d6e2d4006829da00f48c69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL DEFAULT 'created', "orderId" uuid, CONSTRAINT "REL_de6476bcc3a8f852bbe012bcdc" UNIQUE ("orderId"), CONSTRAINT "PK_683b47912b8b30fe71d1fa22199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "number" character varying NOT NULL, "pointId" uuid, "clientId" uuid, "statusId" uuid, "billId" uuid, CONSTRAINT "REL_bbd901ebff961f31c6038c4e2a" UNIQUE ("billId"), CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "point" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "address" character varying NOT NULL, "tenantId" uuid, CONSTRAINT "PK_391f59a9491a08961038a615371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "brand_name" character varying NOT NULL, "legal_name" character varying NOT NULL, CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "s_police" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_f7269c1ef88db2975bd72f2a2c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "policy_permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "create" boolean NOT NULL DEFAULT false, "read" boolean NOT NULL DEFAULT false, "update_" boolean NOT NULL DEFAULT false, "delete" boolean NOT NULL DEFAULT false, "execute" boolean NOT NULL DEFAULT false, "conditions" jsonb array NOT NULL DEFAULT '{}', "system" boolean NOT NULL DEFAULT false, "policyId" uuid, "user_roleId" uuid, CONSTRAINT "PK_53899199bf52d7cf51b4f389879" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL, "tenantId" uuid, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "phone" character varying NOT NULL, "password" character varying NOT NULL, "email" character varying NOT NULL DEFAULT '', "name" character varying NOT NULL DEFAULT '', "cashiers_name" character varying NOT NULL DEFAULT '', "tenantId" uuid, CONSTRAINT "UQ_8e1f623798118e629b46a9e6299" UNIQUE ("phone"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "refresh_token" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "component_categories_component_category" ("componentId" uuid NOT NULL, "componentCategoryId" uuid NOT NULL, CONSTRAINT "PK_7f109aaa2d13affcb1038424a9d" PRIMARY KEY ("componentId", "componentCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b86c942f3a24bf1e685d8f7a72" ON "component_categories_component_category" ("componentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a1abbcf87c188d1419704fb0f" ON "component_categories_component_category" ("componentCategoryId") `);
        await queryRunner.query(`CREATE TABLE "product_categories_product_category" ("productId" uuid NOT NULL, "productCategoryId" uuid NOT NULL, CONSTRAINT "PK_e119df8aaf628a1157cf1263097" PRIMARY KEY ("productId", "productCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37c2bc279249bec81521f8fe89" ON "product_categories_product_category" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8862dee67b712ea20963c464e8" ON "product_categories_product_category" ("productCategoryId") `);
        await queryRunner.query(`CREATE TABLE "sale_point_order_types_order_type" ("salePointId" uuid NOT NULL, "orderTypeId" uuid NOT NULL, CONSTRAINT "PK_33f7035836db29dad034c3c780d" PRIMARY KEY ("salePointId", "orderTypeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b853859521dc90f9639a88c107" ON "sale_point_order_types_order_type" ("salePointId") `);
        await queryRunner.query(`CREATE INDEX "IDX_962a7c9bfde732e18140daf928" ON "sale_point_order_types_order_type" ("orderTypeId") `);
        await queryRunner.query(`CREATE TABLE "user_roles_role" ("userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_b47cd6c84ee205ac5a713718292" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f9286e6c25594c6b88c108db7" ON "user_roles_role" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4be2f7adf862634f5f803d246b" ON "user_roles_role" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "component" ADD CONSTRAINT "FK_9d911e3759eb85a6dab0ecfab4f" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "component_category" ADD CONSTRAINT "FK_cc4f9f3d2756789deb826c84ceb" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumption_component" ADD CONSTRAINT "FK_ccfd7c2edbd8fef7ec89d70a06b" FOREIGN KEY ("componentId") REFERENCES "component"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consumption_component" ADD CONSTRAINT "FK_b08e7fcbb7df084ac65c8dcccbc" FOREIGN KEY ("for_product") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_51b4f57c431ef73d929d42c7cdd" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_8c3c983ded60438088b6d8059bc" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status" ADD CONSTRAINT "FK_6092d24f773f28f1ac9dd48ce82" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_link" ADD CONSTRAINT "FK_ce33e998d09b7fd740b4ba893c6" FOREIGN KEY ("orderTypeId") REFERENCES "order_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_link" ADD CONSTRAINT "FK_06445ca6fcd97cec9e94044ca94" FOREIGN KEY ("statusId") REFERENCES "order_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_type" ADD CONSTRAINT "FK_5ab2b6db84694c8c3c62a427d66" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account" ADD CONSTRAINT "FK_94d7bb757d87040432b066da9c9" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD CONSTRAINT "FK_1c4f02d4e2bf20ea4fa9aff167d" FOREIGN KEY ("pointTenantid") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_link" ADD CONSTRAINT "FK_d302f73857e753a46f5e3c87c3e" FOREIGN KEY ("payment_method", "payment_method") REFERENCES "payment_method"("id","pointId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_link" ADD CONSTRAINT "FK_bb97d1b587096e0e28416a1ba4b" FOREIGN KEY ("sale_point") REFERENCES "sale_point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_link" ADD CONSTRAINT "FK_af213d84714902163a69f69bd88" FOREIGN KEY ("bank_account") REFERENCES "bank_account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_point" ADD CONSTRAINT "FK_054157be114872caeb1fe26924e" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client" ADD CONSTRAINT "FK_810b65a0776d2aa7bd93115a682" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" ADD CONSTRAINT "FK_637c8e242e8bb67e7c6f1e2eafc" FOREIGN KEY ("statusId") REFERENCES "order_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" ADD CONSTRAINT "FK_6f5080103d3640740058e53c2c5" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" ADD CONSTRAINT "FK_bde7af221e0ba9854cc5abe507a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill" ADD CONSTRAINT "FK_de6476bcc3a8f852bbe012bcdce" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_4623baae59240b36348ae0d89a5" FOREIGN KEY ("pointId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_9b27855a9c2ade186e5c55d1ec3" FOREIGN KEY ("clientId") REFERENCES "client"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_3b6667bfe775fa39753ca6af2dc" FOREIGN KEY ("statusId") REFERENCES "order_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_bbd901ebff961f31c6038c4e2ad" FOREIGN KEY ("billId") REFERENCES "bill"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point" ADD CONSTRAINT "FK_0ed3b09443d24924a025468306f" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_permission" ADD CONSTRAINT "FK_c8b6335da8d361c1a1f12261b4b" FOREIGN KEY ("policyId") REFERENCES "s_police"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_permission" ADD CONSTRAINT "FK_4be4296a8db0f4d140d58903315" FOREIGN KEY ("user_roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_1751a572e91385a09d41c624714" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_685bf353c85f23b6f848e4dcded" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token" ADD CONSTRAINT "FK_94f168faad896c0786646fa3d4a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "component_categories_component_category" ADD CONSTRAINT "FK_b86c942f3a24bf1e685d8f7a723" FOREIGN KEY ("componentId") REFERENCES "component"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "component_categories_component_category" ADD CONSTRAINT "FK_8a1abbcf87c188d1419704fb0fa" FOREIGN KEY ("componentCategoryId") REFERENCES "component_category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_categories_product_category" ADD CONSTRAINT "FK_37c2bc279249bec81521f8fe89b" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_categories_product_category" ADD CONSTRAINT "FK_8862dee67b712ea20963c464e88" FOREIGN KEY ("productCategoryId") REFERENCES "product_category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sale_point_order_types_order_type" ADD CONSTRAINT "FK_b853859521dc90f9639a88c1071" FOREIGN KEY ("salePointId") REFERENCES "sale_point"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sale_point_order_types_order_type" ADD CONSTRAINT "FK_962a7c9bfde732e18140daf928b" FOREIGN KEY ("orderTypeId") REFERENCES "order_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" ADD CONSTRAINT "FK_5f9286e6c25594c6b88c108db77" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" ADD CONSTRAINT "FK_4be2f7adf862634f5f803d246b8" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles_role" DROP CONSTRAINT "FK_4be2f7adf862634f5f803d246b8"`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" DROP CONSTRAINT "FK_5f9286e6c25594c6b88c108db77"`);
        await queryRunner.query(`ALTER TABLE "sale_point_order_types_order_type" DROP CONSTRAINT "FK_962a7c9bfde732e18140daf928b"`);
        await queryRunner.query(`ALTER TABLE "sale_point_order_types_order_type" DROP CONSTRAINT "FK_b853859521dc90f9639a88c1071"`);
        await queryRunner.query(`ALTER TABLE "product_categories_product_category" DROP CONSTRAINT "FK_8862dee67b712ea20963c464e88"`);
        await queryRunner.query(`ALTER TABLE "product_categories_product_category" DROP CONSTRAINT "FK_37c2bc279249bec81521f8fe89b"`);
        await queryRunner.query(`ALTER TABLE "component_categories_component_category" DROP CONSTRAINT "FK_8a1abbcf87c188d1419704fb0fa"`);
        await queryRunner.query(`ALTER TABLE "component_categories_component_category" DROP CONSTRAINT "FK_b86c942f3a24bf1e685d8f7a723"`);
        await queryRunner.query(`ALTER TABLE "token" DROP CONSTRAINT "FK_94f168faad896c0786646fa3d4a"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_685bf353c85f23b6f848e4dcded"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_1751a572e91385a09d41c624714"`);
        await queryRunner.query(`ALTER TABLE "policy_permission" DROP CONSTRAINT "FK_4be4296a8db0f4d140d58903315"`);
        await queryRunner.query(`ALTER TABLE "policy_permission" DROP CONSTRAINT "FK_c8b6335da8d361c1a1f12261b4b"`);
        await queryRunner.query(`ALTER TABLE "point" DROP CONSTRAINT "FK_0ed3b09443d24924a025468306f"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_bbd901ebff961f31c6038c4e2ad"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_3b6667bfe775fa39753ca6af2dc"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_9b27855a9c2ade186e5c55d1ec3"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_4623baae59240b36348ae0d89a5"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP CONSTRAINT "FK_de6476bcc3a8f852bbe012bcdce"`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" DROP CONSTRAINT "FK_bde7af221e0ba9854cc5abe507a"`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" DROP CONSTRAINT "FK_6f5080103d3640740058e53c2c5"`);
        await queryRunner.query(`ALTER TABLE "order_status_transactions" DROP CONSTRAINT "FK_637c8e242e8bb67e7c6f1e2eafc"`);
        await queryRunner.query(`ALTER TABLE "client" DROP CONSTRAINT "FK_810b65a0776d2aa7bd93115a682"`);
        await queryRunner.query(`ALTER TABLE "sale_point" DROP CONSTRAINT "FK_054157be114872caeb1fe26924e"`);
        await queryRunner.query(`ALTER TABLE "payment_link" DROP CONSTRAINT "FK_af213d84714902163a69f69bd88"`);
        await queryRunner.query(`ALTER TABLE "payment_link" DROP CONSTRAINT "FK_bb97d1b587096e0e28416a1ba4b"`);
        await queryRunner.query(`ALTER TABLE "payment_link" DROP CONSTRAINT "FK_d302f73857e753a46f5e3c87c3e"`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP CONSTRAINT "FK_1c4f02d4e2bf20ea4fa9aff167d"`);
        await queryRunner.query(`ALTER TABLE "bank_account" DROP CONSTRAINT "FK_94d7bb757d87040432b066da9c9"`);
        await queryRunner.query(`ALTER TABLE "order_type" DROP CONSTRAINT "FK_5ab2b6db84694c8c3c62a427d66"`);
        await queryRunner.query(`ALTER TABLE "order_status_link" DROP CONSTRAINT "FK_06445ca6fcd97cec9e94044ca94"`);
        await queryRunner.query(`ALTER TABLE "order_status_link" DROP CONSTRAINT "FK_ce33e998d09b7fd740b4ba893c6"`);
        await queryRunner.query(`ALTER TABLE "order_status" DROP CONSTRAINT "FK_6092d24f773f28f1ac9dd48ce82"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_8c3c983ded60438088b6d8059bc"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_51b4f57c431ef73d929d42c7cdd"`);
        await queryRunner.query(`ALTER TABLE "consumption_component" DROP CONSTRAINT "FK_b08e7fcbb7df084ac65c8dcccbc"`);
        await queryRunner.query(`ALTER TABLE "consumption_component" DROP CONSTRAINT "FK_ccfd7c2edbd8fef7ec89d70a06b"`);
        await queryRunner.query(`ALTER TABLE "component_category" DROP CONSTRAINT "FK_cc4f9f3d2756789deb826c84ceb"`);
        await queryRunner.query(`ALTER TABLE "component" DROP CONSTRAINT "FK_9d911e3759eb85a6dab0ecfab4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4be2f7adf862634f5f803d246b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f9286e6c25594c6b88c108db7"`);
        await queryRunner.query(`DROP TABLE "user_roles_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_962a7c9bfde732e18140daf928"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b853859521dc90f9639a88c107"`);
        await queryRunner.query(`DROP TABLE "sale_point_order_types_order_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8862dee67b712ea20963c464e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37c2bc279249bec81521f8fe89"`);
        await queryRunner.query(`DROP TABLE "product_categories_product_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a1abbcf87c188d1419704fb0f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b86c942f3a24bf1e685d8f7a72"`);
        await queryRunner.query(`DROP TABLE "component_categories_component_category"`);
        await queryRunner.query(`DROP TABLE "token"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "policy_permission"`);
        await queryRunner.query(`DROP TABLE "s_police"`);
        await queryRunner.query(`DROP TABLE "tenant"`);
        await queryRunner.query(`DROP TABLE "point"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`DROP TABLE "order_status_transactions"`);
        await queryRunner.query(`DROP TABLE "client"`);
        await queryRunner.query(`DROP TABLE "sale_point"`);
        await queryRunner.query(`DROP TABLE "payment_link"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TABLE "bank_account"`);
        await queryRunner.query(`DROP TABLE "order_type"`);
        await queryRunner.query(`DROP TABLE "order_status_link"`);
        await queryRunner.query(`DROP TABLE "order_status"`);
        await queryRunner.query(`DROP TABLE "product_category"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "consumption_component"`);
        await queryRunner.query(`DROP TABLE "component_category"`);
        await queryRunner.query(`DROP TABLE "component"`);
    }

}
